name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a sample build step
        run: echo "Building the project..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production  # Points to the protected environment
    steps:
      - name: Deploy the project
        run: echo "Deploying the project..."
